/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function version(): string
/** Parse HTML to JSON using dom_smoothie (Readability port). */
export declare function parseHtml(html: string, url?: string | undefined | null): any
export interface BatchResult {
  ok?: any
  error?: string
}
/** Parse many HTML documents in one JS->Rust call to minimize overhead. */
export declare function parseMany(inputs: Array<[string, string | undefined | null]>): Array<BatchResult>
